# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "Some Android test deployment"
    lane :distribute_internal_android do
      gradle(task: "clean assembleRelease")
      firebase_app_distribution(
            app: "1:805837096359:android:fabf45bed236bc27b4a282",
            testers: "daria-vo@rambler.ru",
            release_notes: "New Android build",
            firebase_cli_path: "/usr/local/bin/firebase",
            firebase_cli_token: "1//0cSDtEGYz4DEgCgYIARAAGAwSNwF-L9Ir2E9byGwlvFmoa-AQc4kxpPx9399TjF4eMy1m6bYBSvST1uakFbhBjla7knkAqoFYvX8",
            apk_path: "../build/app/outputs/apk/release/app-release.apk"    )
    end
end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
